### PR TITLE
[Task-4] Affable Interview New Feature: Multi Users Chat Conversations (Chat Groups)

### PR DESCRIPTION
**Pull request by youssouf-marzouk**
## Description
This PR tries to implement the feature of multi-user conversations or chat groups.

## Notes on your approach and thought process
I needed to update the back-end and front-end to implement this feature, from the Database models to the UI. This proved to be the most complex challenge in my journey with Hatchways so far, primarily due to my unfamiliarity with the technologies in the backend (Sequelize), I had to figure out a lot of stuff on the spot. But even then, I still managed to come up with an implementation for this feature. 

By the time of writing this comment, I'm still working on the implementation, The base idea is working, but still, there is something that can be added to make it better and enhance the general UX.

### CODE REVIEW

**Comment by youssouf-marzouk** [comment]
### Status Update (Thu, 5th May)
#### Things I've worked on:
1- update Quering the conversations that the user is part of from the Database.
2- Update all instances to use the new Database structure.
3- Add the UI for adding users to conversations.
4- Insure the communication between the client and the server.

#### What I will work on next:
1- Implement the unique hash for conversations.
2- Improve the UI:
       - different UI for Chat Groups
       - show which user sent which message
       - hide the users that are already in the conversation when adding more users.
3- Add more checks to make the app more secure and robust, especially in the backend 

#### Blockers:
Mainly the lack of time, I did have that much of it to work on the task due to my responsibilities at my current job. I didn't have a chance to work on the project until the late hours of the day, by that time I was already exhausted so I wasn't that effective.

#### Demo:
https://www.loom.com/share/7a33d2f1fac648cb8f858ac7c5bc878a

**Comment by youssouf-marzouk** [comment]
Hello Swayam, I'm currently working on implementing the conversation hash we discussed during the interview, and I've run into some paradoxical scenarios. I will try to share my observation below, but just to establish some things:
- The hash property will be added to the conversation model, and it will be computed and updated based on the users that take part in that conversation using a hashing function (let us call it `hash`).
- The hash value of a conversation will be updated each time a new user is added to that conversation based on the Id of this user and all the Ids of the other users of that conversation.
- This hash property will be used to identify conversations based on their users since each user Id is unique, and `hash` will have a unique output for each unique input, the hash will mostly be unique in all cases, but there are some loopholes that I will try to highlight.

**Scenarios 1**
Let us imagine User1 sending a message to User2, this is the first time he sends a message to User2, this will create a conversation on the DB. `hash` will get to work and generate a hash code based on Id1 (User1), and Id2 (User2). User2 replies to User1 with a new message, the API will handle the request, and we know that we've already created a conversation between these two users, so we should be able to query it using the hash code, so `hash` should return us the same hash code so that we can use it to find that conversation. This will require `hash` to have the same output no matter the order of the input elements, in other words: `hash([Id1, Id2]) === hash([Id2, Id1])`.


**Scenario 2**
Now let us imagine Three users (User1, User2, User3). User1 has a conversation with both User2 and User3. User2 adds User3 to the conversation between him and User1, and User3 does the same. This will result in two new Chat Groups with the same users. The issue is that in the database, the two conversations will have the same hash because we've agreed on **Scenarios 1** that the hash function should have the same output no matter the order of the input elements. This will lead to situations where you might save a message to the wrong conversation just because they have the same hash.

**Scenarios 1** and **Scenario 2** leave us with a difficult paradox. Even then, I thought of a solution to this issue. Instead of having one hash property, we will have two. The first one (`hash_users`) will be computed based on the users' Ids of that conversation, and a second one (`hash`) will be computed based on the users' Ids **+** the conversation ID. Since the conversation Id is unique for each conversation, the `hash` will be unique for each conversation while the `hash_users` not necessary. And the way that we will use these hashes is that when receiving a call from the client we will get the users' Ids of that conversation and calculate its hash, we will use the result to query the DB for the conversations that have that same hash as the value for the `hash_users` property. After getting these conversations, we will search for the one that the result of hashing its ID and the Users' Ids we have equals the `hash` property for that conversation, this will make sure no matter the situation we will have the right conversation each time.


This is my observation so far, I know it is a bit too long and complicated, and sorry for that. Looking forward to hearing your thought about it and thank you.


**P.S**: After thinking it over, I believe that the solution I've provided above doesn't resolve the issue, I will continue thinking of a good solution for all possible cases and I'm open to any suggestions.

**Comment by swayam18** [comment]
Thanks for the comments

Indeed, these are edge cases, something that the product owners should decide (especially scenario 2). A simple solution could be that the first to create a group chat wins! Meaning, once `User A` and `User B` have added `User C` to a conversation, a conversation between `User B` and `User C` can no longer add `User A` to their conversation. Adding `User A` must take them to the existing group conversation between `A, B and C`

This is exactly how Slack has solved this problem. If you have slack, you can test the above scenario and see that a new group is not created.

As for the hashing, yes the hash must be the same no matter the order of the users. This is trivially achieved by sorting the ids ascending (or descending!) before computing the hash, resulting in a consistent hash no matter the order in which users were added

**Comment by youssouf-marzouk** [comment]
Thank you @swayam18 for the comment, that is pretty cool from Slack, I was thinking of something like Whatsapp where you can create as many groups as you want with any random combination of users (even duplicates), but that is pretty good too.

And yep, that is how I've imagined it myself as well, simply sort the array and then hash it, this will insure the same output no matter the order of the elements of the input as long as they are the same.

As for the comments, I'm posting them to share my thought process and showcase how I encounter problems and how I deal with them.

**Pull request closed without merging**
